agent_name: "PG"

model:
  actor_net: "fc_2layers_128units"
  actor_init_output_scale: 0.01
  actor_std_type: "FIXED"
  action_std: 0.2
  
  critic_net: "fc_2layers_128units"

actor_optimizer:
    type: "SGD"
    learning_rate: 2e-3
 
critic_optimizer:
    type: "SGD"
    learning_rate: 2e-3
 
discount: 0.99
steps_per_iter: 4096
iters_per_output: 50
test_episodes: 32
critic_update_epoch: 5

batch_size: 512
norm_adv_clip: 4.0
action_bound_weight: 10.0